FROM node:20-alpine
WORKDIR /app

RUN apk add --no-cache openssl libc6-compat ffmpeg python3 make g++

COPY package.json package-lock.json* ./
RUN if [ -f package-lock.json ]; then       npm ci --no-audit --no-fund || npm install --no-audit --no-fund;     else       npm install --no-audit --no-fund;     fi

COPY prisma ./prisma
ENV DATABASE_URL="postgresql://dummy:dummy@localhost:5432/dummy?schema=public"
RUN npx prisma generate

COPY . .

CMD ["npm", "run", "worker"]
