#!/bin/bash
set -e

# AUTO CLIPPER - 1 COMMAND VPS INSTALLER
# Usage: curl -fsSL https://raw.githubusercontent.com/.../install.sh | sudo bash -s -- --domain clipper.example.com --email admin@example.com
# Or: sudo ./install.sh --domain clipper.example.com --email admin@example.com
# Or simple: sudo ./install.sh (use IP + HTTP)

DOMAIN=""
EMAIL=""
ADMIN_EMAIL="admin@autoclipper.local"
ADMIN_PASS="Admin123!"
SKIP_SWAP=false

while [[ $# -gt 0 ]]; do
  case $1 in
    --domain) DOMAIN="$2"; shift 2;;
    --email) EMAIL="$2"; shift 2;;
    --admin-email) ADMIN_EMAIL="$2"; shift 2;;
    --admin-pass) ADMIN_PASS="$2"; shift 2;;
    --skip-swap) SKIP_SWAP=true; shift;;
    *) shift;;
  esac
done

echo "╔════════════════════════════════════════╗"
echo "║   AUTO CLIPPER VPS INSTALLER v1.0    ║"
echo "║   Ubuntu 20.04/22.04/24.04 Ready      ║"
echo "╚════════════════════════════════════════╝"
echo ""

if [[ $EUID -ne 0 ]]; then
  echo "❌ Jalankan sebagai root: sudo ./install.sh"
  exit 1
fi

OS=$(lsb_release -rs 2>/dev/null || echo "unknown")
echo "📦 OS: Ubuntu $OS"

# 1. Install dependencies
echo "📦 Installing dependencies: docker, git, curl, ufw..."
apt-get update -qq
apt-get install -y -qq docker.io docker-compose-plugin git curl ufw caddy 2>/dev/null || apt-get install -y -qq docker.io docker-compose git curl ufw

systemctl enable --now docker || service docker start
echo "✅ Docker installed: $(docker --version)"

# 2. Setup Swap if RAM < 2GB
RAM_KB=$(grep MemTotal /proc/meminfo | awk '{print $2}')
RAM_MB=$((RAM_KB/1024))
echo "💾 RAM: ${RAM_MB}MB"

if [[ $RAM_MB -lt 2048 && "$SKIP_SWAP" != true ]]; then
  if [[ ! -f /swapfile ]]; then
    echo "⚙️ RAM < 2GB, creating 2GB swap..."
    fallocate -l 2G /swapfile || dd if=/dev/zero of=/swapfile bs=1M count=2048
    chmod 600 /swapfile
    mkswap /swapfile
    swapon /swapfile
    echo '/swapfile none swap sw 0 0' >> /etc/fstab
    echo "✅ Swap 2GB created"
  else
    echo "✅ Swap already exists"
    swapon /swapfile || true
  fi
else
  echo "✅ RAM OK, skip swap"
fi

# 3. Setup project dir
INSTALL_DIR="/opt/auto-clipper"
if [[ -f "./docker-compose.prod.yml" ]]; then
  INSTALL_DIR=$(pwd)
  echo "📁 Using current dir: $INSTALL_DIR"
else
  echo "📁 Installing to $INSTALL_DIR"
  if [[ ! -d "$INSTALL_DIR" ]]; then
    # If we are running from curl, clone
    if [[ ! -f "./install.sh" ]]; then
      git clone https://github.com/andriasssssss/auto-clipper.git $INSTALL_DIR || mkdir -p $INSTALL_DIR
    else
      mkdir -p $INSTALL_DIR
      cp -r . $INSTALL_DIR/ 2>/dev/null || true
    fi
  fi
  cd $INSTALL_DIR
fi

# 4. Generate .env if not exists
if [[ ! -f .env ]]; then
  echo "🔑 Generating .env..."
  JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n1)
  POSTGRES_PASS=$(openssl rand -hex 16 2>/dev/null || echo "postgres$(date +%s)")
  REDIS_PASS=$(openssl rand -hex 16 2>/dev/null || echo "redis$(date +%s)")

  if [[ -z "$DOMAIN" ]]; then
    IP=$(curl -s ifconfig.me || hostname -I | awk '{print $1}')
    APP_URL="http://$IP:3000"
  else
    APP_URL="https://$DOMAIN"
  fi

  cat > .env <<EOF
# AUTO GENERATED by install.sh $(date)
DATABASE_URL="postgresql://postgres:${POSTGRES_PASS}@postgres:5432/autoclipper?schema=public"
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${POSTGRES_PASS}
POSTGRES_DB=autoclipper
REDIS_URL="redis://:${REDIS_PASS}@redis:6379"
REDIS_PASSWORD=${REDIS_PASS}
JWT_SECRET="${JWT_SECRET}"
NEXT_PUBLIC_APP_URL="${APP_URL}"
STORAGE_PATH="./uploads"
OUTPUT_PATH="./outputs"
AI_PROVIDER="mock"
OPENAI_API_KEY=""
DOMAIN="${DOMAIN}"
EMAIL="${EMAIL}"
ADMIN_EMAIL="${ADMIN_EMAIL}"
ADMIN_PASSWORD="${ADMIN_PASS}"
EOF
  echo "✅ .env generated: APP_URL=$APP_URL"
else
  echo "✅ .env exists, skip generate"
fi

# 5. Docker compose prod
echo "🐳 Building Docker images (prod)..."
if [[ -f docker-compose.prod.yml ]]; then
  COMPOSE_FILE="docker-compose.prod.yml"
else
  COMPOSE_FILE="docker-compose.yml"
fi

docker compose -f $COMPOSE_FILE down 2>/dev/null || docker-compose -f $COMPOSE_FILE down 2>/dev/null || true
docker compose -f $COMPOSE_FILE build --no-cache app worker 2>/dev/null || docker-compose -f $COMPOSE_FILE build app worker

echo "🚀 Starting containers..."
docker compose -f $COMPOSE_FILE up -d postgres redis 2>/dev/null || docker-compose -f $COMPOSE_FILE up -d postgres redis

echo "⏳ Waiting postgres healthy (30s)..."
for i in {1..30}; do
  if docker compose -f $COMPOSE_FILE exec -T postgres pg_isready -U postgres >/dev/null 2>&1; then
    echo "✅ Postgres ready"
    break
  fi
  sleep 1
done

docker compose -f $COMPOSE_FILE up -d app worker 2>/dev/null || docker-compose -f $COMPOSE_FILE up -d app worker

echo "⏳ Waiting app healthy..."
sleep 10

# 6. Prisma migrate
echo "🗄️ Running Prisma migrate..."
docker compose -f $COMPOSE_FILE exec -T app npx prisma migrate deploy 2>/dev/null || docker compose -f $COMPOSE_FILE exec -T app npx prisma db push --accept-data-loss 2>/dev/null || echo "⚠️ Migrate failed, will try on next restart"

# 7. Seed admin
echo "👤 Creating admin user: $ADMIN_EMAIL"
docker compose -f $COMPOSE_FILE exec -T app node -e "
const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');
(async () => {
  const p = new PrismaClient();
  const hash = await bcrypt.hash('${ADMIN_PASS}', 10);
  await p.user.upsert({
    where: { email: '${ADMIN_EMAIL}' },
    update: { passwordHash: hash, role: 'ADMIN' },
    create: { email: '${ADMIN_EMAIL}', passwordHash: hash, name: 'Admin', role: 'ADMIN' }
  });
  console.log('Admin created');
  await p.\$disconnect();
})();
" 2>/dev/null || echo "⚠️ Admin seed failed, you can create via dashboard register then set role ADMIN in DB"

# 8. UFW
echo "🔥 Setting up UFW..."
ufw --force enable 2>/dev/null || true
ufw allow 22/tcp 2>/dev/null || true
ufw allow 80/tcp 2>/dev/null || true
ufw allow 443/tcp 2>/dev/null || true
ufw allow 3000/tcp 2>/dev/null || true

# 9. Install autoclipper CLI
echo "🔧 Installing autoclipper CLI..."
cp ./autoclipper /usr/local/bin/autoclipper 2>/dev/null || cp ./scripts/autoclipper /usr/local/bin/autoclipper 2>/dev/null || true
chmod +x /usr/local/bin/autoclipper 2>/dev/null || true

# 10. Summary
IP=$(curl -s ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}' | head -n1)
if [[ -n "$DOMAIN" ]]; then
  URL="https://$DOMAIN"
else
  URL="http://$IP:3000"
fi

echo ""
echo "╔════════════════════════════════════════╗"
echo "║   ✅ AUTO CLIPPER INSTALLED!         ║"
echo "╚════════════════════════════════════════╝"
echo ""
echo "🌐 URL: $URL"
echo "👤 Admin: $ADMIN_EMAIL"
echo "🔑 Pass: $ADMIN_PASS"
echo ""
echo "📋 Commands:"
echo "   autoclipper status    - cek status"
echo "   autoclipper logs      - lihat logs"
echo "   autoclipper update    - update app"
echo "   autoclipper backup    - backup DB + files"
echo "   docker compose -f $COMPOSE_FILE ps"
echo "   docker compose -f $COMPOSE_FILE logs -f app worker"
echo ""
echo "📁 Install dir: $INSTALL_DIR"
echo "📄 Env: $INSTALL_DIR/.env"
echo ""
echo "⚠️ Jika pakai domain, pastikan DNS A record $DOMAIN -> $IP"
echo "   Caddy akan auto SSL Let's Encrypt."
echo ""
echo "🎉 Happy clipping!"
